# Generated by Django 4.2.2 on 2023-06-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_alter_menuitems_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='category',
        ),
    ]
